### ISSUE TITLE
Top menu padding is not the same as the design

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website#26]
Current:

![image](https://github.com/user-attachments/assets/b747dc0a-8c21-4166-aa84-2e8e4fc1557b)

Expected:

![image](https://github.com/user-attachments/assets/a4a8f923-526c-4087-8197-75cf63e289be)

### Subtasks

- [ ] The current one is still higher
- [x] Margin between items is larger.
- [x] Font size is larger.

**Comment by josecelano** [comment]
Hi @grmbyrn, in the [PR](https://github.com/torrust/torrust-website-v2/pull/44) only two subtasks were fixed. The items are still not vertically aligned.
